<?php

namespace AppBundle\Repository;

/**
 * EconomicActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EconomicActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
