<?php

namespace AppBundle\Repository;

/**
 * HistorySessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistorySessionRepository extends \Doctrine\ORM\EntityRepository
{
}
