<?php

namespace AppBundle\Repository;

/**
 * HistoryRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
