<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Taxpayer;

/**
 * TaxpayerPointOfSaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxpayerPointOfSaleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTaxpayer(Taxpayer $taxpayer)
    {
        $db = $this->createQueryBuilder('pos');

        $db->select('pos')
            ->join('pos.taxpayerBankAccount', 'ba')
            ->where('ba.taxpayer = :taxpayer')
            ->setParameter(':taxpayer', $taxpayer);

        return $db->getQuery()->execute();
    }
}
