<?php

namespace AppBundle\Repository;

/**
 * TaxpayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxpayerRepository extends \Doctrine\ORM\EntityRepository
{
}
