<?php

namespace AppBundle\Repository;

/**
 * TaxpayerBankAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxpayerBankAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
