<?php

namespace AppBundle\Repository;

/**
 * TaxReturnEconomicActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxReturnEconomicActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
