<?php

namespace AppBundle\Repository;

/**
 * TaxReturnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxReturnRepository extends \Doctrine\ORM\EntityRepository
{
}
