<?php

namespace AppBundle\Repository;

/**
 * WebsiteMainSlideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteMainSlideRepository extends \Doctrine\ORM\EntityRepository
{
}
