<?php

namespace AppBundle\Repository;

/**
 * WebsiteSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
