<?php

namespace AppBundle\Repository;

/**
 * WebsiteNoticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteNoticeRepository extends \Doctrine\ORM\EntityRepository
{
}
