<?php

namespace AppBundle\Repository;

/**
 * WebsiteActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
