<?php

namespace AppBundle\Repository;

/**
 * WebsiteRelatedPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteRelatedPageRepository extends \Doctrine\ORM\EntityRepository
{
}
