<?php

namespace AppBundle\Repository;

/**
 * WebsiteVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
