security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ASSISTANT: ROLE_USER
        ROLE_FISCAL: ROLE_USER
        ROLE_WEBSITE_MANAGER: ROLE_USER
        ROLE_ADMIN: [ ROLE_ASSISTANT, ROLE_FISCAL, ROLE_WEBSITE_MANAGER ]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
            logout_on_user_change: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/system/admin, role: ROLE_ADMIN }
        - { path: ^/system/tax, role: ROLE_FISCAL }
        - { path: ^/system/cms, role: ROLE_WEBSITE_MANAGER }
        - { path: ^/system/assistance, role: ROLE_ASSISTANT }
        - { path: ^/system, role: ROLE_USER }
